FROM --platform=arm64 ubuntu:22.04
ENV DEBIAN_FRONTEND noninteractive

ENV PYTHONUNBUFFERED=1
# Set MODELPATH environment variable
ENV MODELPATH=/opt/models/llm_model.bin

# The working directory in the Docker image
WORKDIR /app

# Install system dependencies
RUN apt-get update && \
    apt-get install -y \
    g++ \
    make \
    cmake \
    unzip \
    libcurl4-openssl-dev \
    python3 \
    python3-pip \
    python3-dev \
    git \
    wget \
    libclblast-dev \
    libopenblas-dev \
    && rm -rf /var/lib/apt/lists/*

# Create a models directory
RUN mkdir -p /opt/models
RUN wget -O ${MODELPATH} "https://huggingface.co/TheBloke/stablelm-zephyr-3b-GGUF/resolve/main/stablelm-zephyr-3b.Q5_K_M.gguf"
# Copy requirements.txt and install Python dependencies
COPY requirements.txt ./requirements.txt
COPY main.py .

RUN pip3 install -r requirements.txt && \
    pip3 install awslambdaric 
# Set working directory to function root directory
WORKDIR ${FUNCTION_DIR}
ENTRYPOINT [ "/usr/bin/python3", "-m", "awslambdaric" ]
CMD [ "main.handler" ]
